### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by alexgorgos** [everythinginjs/gatsby-source-menus-strapi-plugin#1]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/6532770/184195497-8e018881-fa9c-4755-9248-256680f68698.png">

Gatsby 4.20.0
Strapi 4.3.4

**Comment by everythinginjs** [comment]
@alexgorgos  Thanks for the issue you created it seems Menus Strapi Plugin has gone under a major update. I just fixed the package and released it. Have a nice time 👋.
